[package]
name = "cipher"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
kaspa-addresses = {git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0"}
chacha20poly1305 = "0.10.1"
hex = "0.4.3"
k256 = {version = "0.13.4", features = ["ecdh", "arithmetic"]}
sha2 = "0.10.8"
secp256k1 = "0.29.1"
wasm-bindgen = "0.2.100"
kaspa-wallet-keys = {git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0"}
# needed for randomness
uuid = {version = "1.16.0", features = ["v4", "fast-rng", "js"]}

[dev-dependencies]
kaspa-wrpc-client = {git = "https://github.com/kaspanet/rusty-kaspa.git", tag = "v1.0.0"}
