name: Build

on:
  push:
    branches:
      - staging
      - master
      # todo remove
      - chore/mobile

jobs:
  build-cipher-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # install rust
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: 1.86.0
          target: wasm32-unknown-unknown
          # key based on branch name
          cache-shared-key: cipher-wasm-build-cache-${{ github.ref_name }}
          cache-workspaces: ./cipher -> target

      - name: Build Cipher Wasm
        # install wasm-pack, move to ./cipher and build with wasm-pack
        run: |
          cargo install wasm-pack
          cd ./cipher
          wasm-pack build --target web --release -d ../cipher-wasm

      - name: Cache WASM
        id: cipher-wasm-cache
        uses: actions/cache/save@v4
        with:
          path: cipher-wasm
          key: cipher-wasm-${{ github.ref_name }}
# uses: dsaltares/fetch-gh-release-asset@master
# with:
#   repo: 'dsaltares/godot-wild-jam-18'
#   version: 'tags/v0.1.18'
#   file: 'plague-linux.zip'
#   token: ${{ secrets.GITHUB_TOKEN }}
